<style>
    h1 {
            text-align: center;
            margin-bottom: 28px;
            font-size: 24px;
    }
    footer {
            text-align: center;
            margin-top: 28px;
            font-size: 16px;
    }
    a {
        text-decoration: none;
    }
</style>
<footer>
    <hr>
    <a href="mailto:106399199@student.swin.edu.au">Contact Us</a>
    <br>
    <small>&copy; copyrighted 2026</small>
</footer>